---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Set ufw default deny incoming
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set ufw default allow outgoing
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH through ufw
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow tailscale interface
  community.general.ufw:
    rule: allow
    interface: tailscale0
    direction: in

- name: Enable ufw
  community.general.ufw:
    state: enabled
