---
- name: Include package tasks
  ansible.builtin.import_tasks: packages.yml

- name: Include admin user tasks
  ansible.builtin.import_tasks: user.yml

- name: Include tailscale tasks
  ansible.builtin.import_tasks: tailscale.yml

- name: Include SSH hardening tasks
  ansible.builtin.import_tasks: hardening.yml

- name: Include firewall tasks
  ansible.builtin.import_tasks: firewall.yml

- name: Include fail2ban tasks
  ansible.builtin.import_tasks: fail2ban.yml

- name: Include unattended-upgrades tasks
  ansible.builtin.import_tasks: unattended.yml
  when: unattended_upgrades_enabled | bool
